/**
 * @file Automatically generated by barrelsby.
 */

export * from './redis.config';
export * from './redis.module';
export * from './redis.service.spec';
export * from './redis.service';
export * from './redis.interface';
